name: Auto Fix Failed Build

on:
  workflow_run:
    workflows: ["Your CI Workflow"]
    types:
      - completed

jobs:
  auto-fix:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
        
      - name: AI Code Modifier
        uses: your-action-repo/AI-Code-Modifier@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
        env:
          RUN_ID: ${{ github.event.workflow_run.id }}